sensor_msgs/Image imL
sensor_msgs/Image imR
---
stereo_msgs/DisparityImage dispH
stereo_msgs/DisparityImage dispV
stereo_msgs/DisparityImage dispC
rh_stereo_proc/foveatedstack fdispH
rh_stereo_proc/foveatedstack fdispV
rh_stereo_proc/foveatedstack fdispC
